// RCCMS script.js (Full functionality + Dhara/Year wise reports, disposal date range)
let registrations = JSON.parse(localStorage.getItem('rccms_registrations')) || (window.PRELOADED_REGISTRATIONS || []);
let disposals = JSON.parse(localStorage.getItem('rccms_disposals')) || (window.PRELOADED_DISPOSALS || []);
let currentEditIndex = -1;
document.addEventListener('DOMContentLoaded',()=>{
    document.getElementById('currentDate').innerHTML = new Date().toLocaleDateString('en-IN',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
    document.getElementById('regDate').valueAsDate = new Date();
    document.getElementById('dispDate').valueAsDate = new Date();
    let today = new Date();
    document.getElementById('mprFromDate').valueAsDate = new Date(today.getFullYear(), today.getMonth(), 1);
    document.getElementById('mprToDate').valueAsDate = today;
    document.getElementById('dispReportFrom').valueAsDate = new Date(today.getFullYear(), today.getMonth()-1, 1);
    document.getElementById('dispReportTo').valueAsDate = today;
    refreshAll();
});
function saveData(){localStorage.setItem('rccms_registrations',JSON.stringify(registrations));localStorage.setItem('rccms_disposals',JSON.stringify(disposals));}
function showToast(msg,type='success'){let t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),3000);}
function showTab(tabId){document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.nav-tab').forEach(t=>t.classList.remove('active'));document.getElementById(tabId).classList.add('active');event.target.classList.add('active');refreshAll();if(tabId==='reports'){generateDharaWiseReport();generateYearWiseReport();}}
function getPendingFiles(){return registrations.filter(r=>!disposals.find(d=>d.rrcms===r.rrcms));}
function formatDate(d){if(!d)return'-';let dd=new Date(d);return isNaN(dd)?d:dd.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});}
function getAgeCategory(days){if(days<=180)return{label:'Upto 6 Months',class:'badge-green'};if(days<=365)return{label:'6-12 Months',class:'badge-yellow'};if(days<=730)return{label:'1-2 Years',class:'badge-orange'};if(days<=1095)return{label:'2-3 Years',class:'badge-orange'};if(days<=1825)return{label:'3-5 Years',class:'badge-red'};if(days<=3650)return{label:'5-10 Years',class:'badge-red'};if(days<=7300)return{label:'10-20 Years',class:'badge-purple'};if(days<=10950)return{label:'20-30 Years',class:'badge-purple'};if(days<=14600)return{label:'30-40 Years',class:'badge-gray'};return{label:'More Than 40 Years',class:'badge-gray'};}
function updateLoadedCounts(){document.getElementById('loadedReg').textContent=registrations.length;document.getElementById('loadedDisp').textContent=disposals.length;document.getElementById('loadedPending').textContent=getPendingFiles().length;}
function refreshAll(){updateDashboard();renderRegistrations();updateDisposalDropdown();renderDisposals();updateFilters();renderPending();generateDharaWiseReport();generateYearWiseReport();}
function registerFile(){let rrcms=document.getElementById('regRRCMS').value.trim(),date=document.getElementById('regDate').value,stream=document.getElementById('regStream').value.trim(),year=document.getElementById('regYear').value,applicant=document.getElementById('regApplicant').value.trim(),village=document.getElementById('regVillage').value.trim();if(!rrcms||!date||!stream||!year)return showToast('Fill all required fields!','error');if(registrations.find(r=>r.rrcms===rrcms))return showToast('RRCMS exists!','error');registrations.push({sno:registrations.length+1,rrcms,regDate:date,stream,regYear:parseInt(year),applicant,village});saveData();showToast('Registered!');document.getElementById('regRRCMS').value='';document.getElementById('regStream').value='';document.getElementById('regYear').value='';document.getElementById('regApplicant').value='';document.getElementById('regVillage').value='';refreshAll();}
function renderRegistrations(){let tbody=document.getElementById('registrationTableBody'),search=document.getElementById('regSearch')?.value.toLowerCase()||'',filtered=registrations.filter(r=>search?r.rrcms.toLowerCase().includes(search)||r.stream.toLowerCase().includes(search)||(r.applicant||'').toLowerCase().includes(search):true);filtered.sort((a,b)=>new Date(b.regDate)-new Date(a.regDate));tbody.innerHTML=filtered.map((r,i)=>{let d=disposals.find(dd=>dd.rrcms===r.rrcms);return`<tr><td>${i+1}</td><td><strong>${r.rrcms}</strong></td><td>${formatDate(r.regDate)}</td><td><span class="stream-tag">${r.stream}</span></td><td>${r.regYear}</td><td>${r.applicant||'-'}</td><td>${r.village||'-'}</td><td>${d?'<span class="badge badge-green">Disposed</span>':'<span class="badge badge-orange">Pending</span>'}</td><td class="no-print"><button class="btn btn-primary" style="padding:4px 10px;" onclick="editFile('${r.rrcms}')">Edit</button> <button class="btn btn-danger" style="padding:4px 10px;" onclick="deleteFile('${r.rrcms}')">Del</button></td></tr>`}).join('');}
function editFile(rrcms){let f=registrations.find(r=>r.rrcms===rrcms);if(!f)return;currentEditIndex=registrations.findIndex(r=>r.rrcms===rrcms);document.getElementById('editRRCMS').value=f.rrcms;document.getElementById('editDate').value=f.regDate;document.getElementById('editStream').value=f.stream;document.getElementById('editYear').value=f.regYear;document.getElementById('editApplicant').value=f.applicant||'';document.getElementById('editVillage').value=f.village||'';document.getElementById('editModal').classList.add('active');}
function saveEdit(){if(currentEditIndex<0)return;registrations[currentEditIndex].regDate=document.getElementById('editDate').value;registrations[currentEditIndex].stream=document.getElementById('editStream').value;registrations[currentEditIndex].regYear=parseInt(document.getElementById('editYear').value);registrations[currentEditIndex].applicant=document.getElementById('editApplicant').value;registrations[currentEditIndex].village=document.getElementById('editVillage').value;saveData();closeModal();showToast('Updated');refreshAll();}
function closeModal(){document.getElementById('editModal').classList.remove('active');currentEditIndex=-1;}
function deleteFile(rrcms){if(!confirm('Delete permanently?'))return;registrations=registrations.filter(r=>r.rrcms!==rrcms);disposals=disposals.filter(d=>d.rrcms!==rrcms);saveData();showToast('Deleted');refreshAll();}
function updateDisposalDropdown(){let pending=registrations.filter(r=>!disposals.find(d=>d.rrcms===r.rrcms)),sel=document.getElementById('dispRRCMS');sel.innerHTML='<option value="">Select RRCMS</option>'+pending.map(r=>`<option value="${r.rrcms}">${r.rrcms} - ${r.stream}</option>`).join('');}
function searchFilesToDispose(){let term=document.getElementById('disposeSearch').value.trim().toLowerCase(),resDiv=document.getElementById('searchResults');if(!term){resDiv.style.display='none';return;}let matches=registrations.filter(r=>r.rrcms.toLowerCase().includes(term)||r.stream.toLowerCase().includes(term)||r.regYear.toString().includes(term)).slice(0,20);if(!matches.length){resDiv.innerHTML='<div>No files</div>';resDiv.style.display='block';return;}resDiv.innerHTML=matches.map(r=>{let isDisposed=disposals.find(d=>d.rrcms===r.rrcms);return`<div style="padding:8px;border-bottom:1px solid #ccc;cursor:${isDisposed?'not-allowed':'pointer'};background:#fff" onclick="${!isDisposed?`selectFileForDisposal('${r.rrcms}')`:''}"><strong>${r.rrcms}</strong> | ${r.stream} | ${formatDate(r.regDate)} ${isDisposed?'(Disposed)':'<span style="color:green">(Pending)</span>'}</div>`}).join('');resDiv.style.display='block';}
function selectFileForDisposal(rrcms){if(disposals.find(d=>d.rrcms===rrcms)){showToast('Already disposed','error');return;}document.getElementById('dispRRCMS').value=rrcms;loadFileDetails();document.getElementById('disposeSearch').value='';document.getElementById('searchResults').style.display='none';showToast(`Selected ${rrcms}`);}
function clearDisposeSearch(){document.getElementById('disposeSearch').value='';document.getElementById('searchResults').style.display='none';}
function loadFileDetails(){let rrcms=document.getElementById('dispRRCMS').value,f=registrations.find(r=>r.rrcms===rrcms);let div=document.getElementById('fileDetails');if(f){div.style.display='block';document.getElementById('fileDetailText').innerHTML=`RRCMS: ${f.rrcms} | Stream: ${f.stream} | Reg Date: ${formatDate(f.regDate)}`;}else div.style.display='none';}
function disposeFile(){let rrcms=document.getElementById('dispRRCMS').value,date=document.getElementById('dispDate').value,type=document.getElementById('dispType').value,remarks=document.getElementById('dispRemarks').value.trim();if(!rrcms||!date||!type)return showToast('Fill required','error');let file=registrations.find(r=>r.rrcms===rrcms);if(!file||disposals.find(d=>d.rrcms===rrcms))return showToast('Invalid or already disposed','error');disposals.push({rrcms,stream:file.stream,regDate:file.regDate,disposalDate:date,disposalType:type,remarks});saveData();showToast('Disposed');document.getElementById('dispRRCMS').value='';document.getElementById('dispType').value='';document.getElementById('dispRemarks').value='';document.getElementById('fileDetails').style.display='none';refreshAll();}
function renderDisposals(){let tbody=document.getElementById('disposalTableBody'),search=document.getElementById('dispSearch')?.value.toLowerCase()||'',filtered=disposals.filter(d=>search?d.rrcms.toLowerCase().includes(search)||d.stream.toLowerCase().includes(search):true);filtered.sort((a,b)=>new Date(b.disposalDate)-new Date(a.disposalDate));tbody.innerHTML=filtered.map((d,i)=>{let days=Math.ceil((new Date(d.disposalDate)-new Date(d.regDate))/(86400000));return`<tr><td>${i+1}</td><td><strong>${d.rrcms}</strong></td><td>${d.stream}</td><td>${formatDate(d.regDate)}</td><td>${formatDate(d.disposalDate)}</td><td><span class="badge badge-green">${d.disposalType}</span></td><td>${days} days</td><td>${d.remarks||'-'}</td><td><button class="btn btn-danger" onclick="undoDisposal('${d.rrcms}')">Undo</button></td></tr>`}).join('');}
function undoDisposal(rrcms){if(!confirm('Undo disposal?'))return;disposals=disposals.filter(d=>d.rrcms!==rrcms);saveData();showToast('Undone');refreshAll();}
function filterDisposals(){renderDisposals();}
function filterRegistrations(){renderRegistrations();}
function renderPending(){let pending=getPendingFiles(),stream=document.getElementById('pendingStreamFilter').value,year=document.getElementById('pendingYearFilter').value,age=document.getElementById('pendingAgeFilter').value,search=document.getElementById('pendingSearch').value.toLowerCase(),today=new Date();if(stream)pending=pending.filter(r=>r.stream===stream);if(year)pending=pending.filter(r=>r.regYear==year);if(search)pending=pending.filter(r=>r.rrcms.toLowerCase().includes(search));if(age){let [min,max]=age.split('-');if(max)pending=pending.filter(r=>{let days=Math.ceil((today-new Date(r.regDate))/86400000);return days>=+min&&days<+max;});else pending=pending.filter(r=>{let days=Math.ceil((today-new Date(r.regDate))/86400000);return days>=+min.replace('+','');});}
pending.sort((a,b)=>new Date(a.regDate)-new Date(b.regDate));let tbody=document.getElementById('pendingTableBody');tbody.innerHTML=pending.map((r,i)=>{let days=Math.ceil((today-new Date(r.regDate))/86400000),ageCat=getAgeCategory(days);return`<tr><td>${i+1}</td><td><strong>${r.rrcms}</strong></td><td>${formatDate(r.regDate)}</td><td>${r.stream}</td><td>${r.regYear}</td><td>${days}</td><td><span class="badge ${ageCat.class}">${ageCat.label}</span></td><td>${r.applicant||'-'}</td><td>${r.village||'-'}</td></tr>`}).join('');if(!pending.length)tbody.innerHTML='<tr><td colspan="9">No pending files</td></tr>';}
function updateFilters(){let streams=[...new Set(registrations.map(r=>r.stream))],years=[...new Set(registrations.map(r=>r.regYear))].sort((a,b)=>b-a);document.getElementById('pendingStreamFilter').innerHTML='<option value="">All Streams</option>'+streams.map(s=>`<option>${s}</option>`).join('');document.getElementById('pendingYearFilter').innerHTML='<option value="">All Years</option>'+years.map(y=>`<option>${y}</option>`).join('');}
function filterPending(){renderPending();}
function updateDashboard(){let today=new Date(),todayStr=today.toISOString().split('T')[0];document.getElementById('totalFiles').textContent=registrations.length;document.getElementById('disposedFiles').textContent=disposals.length;document.getElementById('pendingFiles').textContent=getPendingFiles().length;document.getElementById('pendingOver5Yrs').textContent=getPendingFiles().filter(r=>(today-new Date(r.regDate))/86400000>1825).length;document.getElementById('todayRegistered').textContent=registrations.filter(r=>r.regDate===todayStr).length;document.getElementById('todayDisposed').textContent=disposals.filter(d=>d.disposalDate===todayStr).length;updateLoadedCounts();let pending=getPendingFiles(),ageCounts={'Upto 6 Months':0,'6 Months - 1 Year':0,'1 - 2 Years':0,'2 - 3 Years':0,'3 - 5 Years':0,'5 - 10 Years':0,'10 - 20 Years':0,'20 - 30 Years':0,'30 - 40 Years':0,'More Than 40 Years':0};pending.forEach(r=>{let days=Math.ceil((today-new Date(r.regDate))/86400000),age=getAgeCategory(days);ageCounts[age.label]++;});let total=pending.length||1,ageBody=document.getElementById('ageAnalysisBody');ageBody.innerHTML=Object.entries(ageCounts).map(([l,c])=>`<tr><td>${l}</td><td><strong>${c}</strong></td><td>${((c/total)*100).toFixed(1)}%</td><td><div class="age-bar"><div class="age-fill" style="width:${(c/total)*100}%"></div></div></td></tr>`).join('');let streams=[...new Set(registrations.map(r=>r.stream))];document.getElementById('streamAnalysisBody').innerHTML=streams.map(s=>{let total=registrations.filter(r=>r.stream===s).length,disp=disposals.filter(d=>d.stream===s).length,pend=total-disp;return`<tr><td>${s}</td><td>${total}</td><td style="color:#e53e3e">${pend}</td><td>${disp}</td><td>${total?((pend/total)*100).toFixed(1):0}%</td></tr>`}).join('');let years=[...new Set(registrations.map(r=>r.regYear))].sort((a,b)=>b-a);document.getElementById('yearAnalysisBody').innerHTML=years.map(y=>{let total=registrations.filter(r=>r.regYear===y).length,disp=disposals.filter(d=>registrations.find(r=>r.rrcms===d.rrcms)?.regYear===y).length,pend=total-disp;return`<tr><td>${y}</td><td>${total}</td><td style="color:#e53e3e">${pend}</td><td>${disp}</td><td>${total?((pend/total)*100).toFixed(1):0}%</td></tr>`}).join('');}
function generateMPR(){let from=new Date(document.getElementById('mprFromDate').value),to=new Date(document.getElementById('mprToDate').value);let initial=registrations.filter(r=>new Date(r.regDate)<from&&(!disposals.find(d=>d.rrcms===r.rrcms)||new Date(disposals.find(d=>d.rrcms===r.rrcms).disposalDate)>=from)).length;let newReg=registrations.filter(r=>new Date(r.regDate)>=from&&new Date(r.regDate)<=to).length;let decided=disposals.filter(d=>new Date(d.disposalDate)>=from&&new Date(d.disposalDate)<=to).length;let pendingAsOn=registrations.filter(r=>new Date(r.regDate)<=to&&(!disposals.find(d=>d.rrcms===r.rrcms)||new Date(disposals.find(d=>d.rrcms===r.rrcms).disposalDate)>to));let bk={0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0};pendingAsOn.forEach(r=>{let days=Math.ceil((to-new Date(r.regDate))/86400000);if(days<=180)bk[0]++;else if(days<=365)bk[1]++;else if(days<=730)bk[2]++;else if(days<=1095)bk[3]++;else if(days<=1825)bk[4]++;else if(days<=3650)bk[5]++;else if(days<=7300)bk[6]++;else if(days<=10950)bk[7]++;else if(days<=14600)bk[8]++;else bk[9]++;});document.getElementById('mprTableBody').innerHTML=`<tr><td>1</td><td style="text-align:left">Assistant Collector (Fastrack), Niwai</td><td>${initial}</td><td>${newReg}</td><td>${decided}</td><td><strong>${pendingAsOn.length}</strong></td><td>${bk[0]}</td><td>${bk[1]}</td><td>${bk[2]}</td><td>${bk[3]}</td><td>${bk[4]}</td><td>${bk[5]}</td><td>${bk[6]}</td><td>${bk[7]}</td><td>${bk[8]}</td><td>${bk[9]}</td></tr>`;}
function exportMPRCSV(){let rows=document.querySelectorAll('#mprTableBody tr');if(!rows.length)return;let csv='S.No.,Office,Initial Pending,New Registered,Decided,Pending,<6M,6-12M,1-2Y,2-3Y,3-5Y,5-10Y,10-20Y,20-30Y,30-40Y,>40Y\n';rows.forEach(row=>{let vals=Array.from(row.querySelectorAll('td')).map(td=>td.innerText.trim());csv+=vals.join(',')+'\n';});downloadCSV(csv,'MPR_Report.csv');}
function exportPendingCSV(){let pending=getPendingFiles(),today=new Date();let csv='S.No,RRCMS,Reg Date,Stream,Year,Pending Days,Age Category,Applicant,Village\n';pending.forEach((r,i)=>{let days=Math.ceil((today-new Date(r.regDate))/86400000),age=getAgeCategory(days);csv+=`${i+1},${r.rrcms},${r.regDate},${r.stream},${r.regYear},${days},${age.label},${r.applicant||''},${r.village||''}\n`;});downloadCSV(csv,'Pending_Files.csv');}
function generateDharaWiseReport(){let streams=[...new Set(registrations.map(r=>r.stream))].sort();let tbody=document.getElementById('dharaWiseBody');tbody.innerHTML=streams.map(s=>{let total=registrations.filter(r=>r.stream===s).length,disp=disposals.filter(d=>d.stream===s).length,pend=total-disp;return`<tr><td>${s}</td><td>${total}</td><td>${disp}</td><td>${pend}</td><td>${total?((disp/total)*100).toFixed(1):0}%</td></tr>`}).join('');}
function generateYearWiseReport(){let years=[...new Set(registrations.map(r=>r.regYear))].sort((a,b)=>b-a);let tbody=document.getElementById('yearWiseBody');tbody.innerHTML=years.map(y=>{let total=registrations.filter(r=>r.regYear===y).length,disp=disposals.filter(d=>registrations.find(r=>r.rrcms===d.rrcms)?.regYear===y).length,pend=total-disp;return`<tr><td>${y}</td><td>${total}</td><td>${disp}</td><td>${pend}</td><td>${total?((disp/total)*100).toFixed(1):0}%</td></tr>`}).join('');}
function generateDisposalDateReport(){let from=document.getElementById('dispReportFrom').value,to=document.getElementById('dispReportTo').value;if(!from||!to){showToast('Select from/to dates','error');return;}let filtered=disposals.filter(d=>d.disposalDate>=from&&d.disposalDate<=to).sort((a,b)=>new Date(b.disposalDate)-new Date(a.disposalDate));let tbody=document.getElementById('disposalDateBody');if(!filtered.length){tbody.innerHTML='<tr><td colspan="7">No disposals in range.</td></tr>';return;}tbody.innerHTML=filtered.map((d,i)=>`<tr><td>${i+1}</td><td><strong>${d.rrcms}</strong></td><td>${d.stream}</td><td>${formatDate(d.regDate)}</td><td>${formatDate(d.disposalDate)}</td><td>${d.disposalType}</td><td>${d.remarks||'-'}</td></tr>`).join('');}
function exportDharaWiseCSV(){let rows=document.querySelectorAll('#dharaWiseBody tr');let csv='Stream (Dhara),Total Registered,Disposed,Pending,Disposal %\n';rows.forEach(r=>{let td=r.querySelectorAll('td');csv+=`${td[0].innerText},${td[1].innerText},${td[2].innerText},${td[3].innerText},${td[4].innerText}\n`;});downloadCSV(csv,'Dhara_Wise_Report.csv');}
function exportYearWiseCSV(){let rows=document.querySelectorAll('#yearWiseBody tr');let csv='Year,Total Registered,Disposed,Pending,Disposal %\n';rows.forEach(r=>{let td=r.querySelectorAll('td');csv+=`${td[0].innerText},${td[1].innerText},${td[2].innerText},${td[3].innerText},${td[4].innerText}\n`;});downloadCSV(csv,'Year_Wise_Report.csv');}
function exportDisposalDateWiseCSV(){let rows=document.querySelectorAll('#disposalDateBody tr');if(rows.length===1&&rows[0].innerText.includes('No disposals')){showToast('No data to export','error');return;}let csv='S.No,RRCMS No,Stream,Registration Date,Disposal Date,Disposal Type,Remarks\n';rows.forEach((r,i)=>{let td=r.querySelectorAll('td');if(td.length>1)csv+=`${td[0].innerText},${td[1].innerText},${td[2].innerText},${td[3].innerText},${td[4].innerText},${td[5].innerText},${td[6].innerText}\n`;});downloadCSV(csv,'Disposal_Date_Range.csv');}
function downloadCSV(csv,name){let blob=new Blob([csv],{type:'text/csv'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();}
function handleTotalFilesUpload(e){let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=ev=>{let lines=ev.target.result.split('\n'),cnt=0;lines.forEach(line=>{let parts=line.split(/[\t,]/).map(p=>p.trim());if(parts.length>=3){let rrcms=parts[1]||parts[0],regDate=parts[2]||parts[1],stream=parts[3]||parts[2],year=parts[4]||new Date(regDate).getFullYear();if(rrcms&&regDate&&!registrations.find(r=>r.rrcms===rrcms)){registrations.push({sno:registrations.length+1,rrcms,regDate:new Date(regDate).toISOString().split('T')[0],stream,regYear:parseInt(year),applicant:'',village:''});cnt++;}});saveData();showToast(`Imported ${cnt} files.`);refreshAll();};reader.readAsText(file);}
function handleDisposalUpload(e){let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=ev=>{let lines=ev.target.result.split('\n'),cnt=0;lines.forEach(line=>{let parts=line.split(/[\t,]/).map(p=>p.trim());let rrcms=parts[0],dispDate=parts[parts.length-1];let reg=registrations.find(r=>r.rrcms===rrcms);if(reg&&!disposals.find(d=>d.rrcms===rrcms)&&dispDate){disposals.push({rrcms,stream:reg.stream,regDate:reg.regDate,disposalDate:new Date(dispDate).toISOString().split('T')[0],disposalType:'Decided',remarks:'Imported'});cnt++;}});saveData();showToast(`Imported ${cnt} disposals.`);refreshAll();};reader.readAsText(file);}
function clearAllData(){if(confirm('Delete ALL data?')){registrations=[];disposals=[];saveData();showToast('All cleared');refreshAll();}}
function exportAllData(){let data={registrations,disposals,exported:new Date().toISOString()};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`RCCMS_backup_${new Date().toISOString().split('T')[0]}.json`;a.click();}
